source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GhostPostClient_Example', :exclusive => true do
  pod "GhostPostClient", :path => "../"
end

target 'GhostPostClient_Tests', :exclusive => true do
  pod "GhostPostClient", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
